deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "OneCX Search Config"
      imageUrl: ""
      iconName: "pi-search-plus"
      displayName: "OneCX Search Config"
      basePath: "/search-config"
