= OneCX Search Config Management

== Licence
This software is licensed under the Apache License, Version 2.0.
You may obtain a copy of the license in the corresponding LICENSE file or visit the link:https://www.apache.org/licenses/LICENSE-2.0[Apache website] for more information.

== Contributing
We welcome contributions from the community.
If you would like to contribute to the development of OneCX Search Config Management Software, please follow our contribution guidelines (tbd).

== What is Search Config Management?
Search Config Management refers to creating and editing Search Configurations usable in context of OneCX applications.

== Key Features
* Search Config Creation and Editing: create and edit Search Config items usable in context of OneCX applications.

== Issue tracking
All OneCX Search Config issues are tracked and maintained at the link:https://xyz.com[issue tracking tool].

== Overview
OneCX Search Config Software is a comprehensive solution for managing Search Config in a user-friendly and efficient manner.
It is a solution that consists of three main components: a backend service, a user interface and a backend-for-frontend (BFF) layer.

The three components of the OneCX Search Config Software are as follows:

. Search Config User Interface (UI)
  The user interface component is based on Angular, a popular JavaScript framework for building dynamic web applications.
  It offers a user-friendly and intuitive interface for interacting with the Search Config system.
  Users can perform actions such as searching and editing of Search Configs.

. Search Config Backend for Frontend (BFF)
  The BFF layer acts as an intermediary between the frontend user interface and the backend service.
  It handles tasks such as data aggregation, transformation, and composition to provide an optimized API for the UI.
  The BFF layer is designed to enhance performance and simplify the integration of the frontend with the backend service.

. Search Config Backend Service (SVC)
  This component provides the core functionality.
  It handles tasks such as storage, retrieval and editing of Search Configs.
  The backend is built cloud native using Quarkus.

Interfaces are based on the TM-Forum standard link:https://github.com/tmforum-apis/TMF667_Document[TMF 667].

== Getting Started
To get started with OneCX Search Config Software, please refer to the following installation and setup instructions specific to each component:

* link:https://onecx.github.io/docs/onecx-search-config/current/onecx-search-config-ui/index.html[OneCX Search Config UI (User Interface) - Getting Started]
* link:https://onecx.github.io/docs/onecx-search-config/current/onecx-search-config-bff/index.html[OneCX Search Config BFF (Backend for Frontend) - Getting Started]
* link:https://onecx.github.io/docs/onecx-search-config/current/onecx-search-config-svc/index.html[OneCX Search Config SVC (Backend) - Getting Started]

For detailed usage instructions and API documentation, please refer to the respective documentation files for each component.

== Roadmap
tbd